"""add qouta to users

Revision ID: 7d9556163367
Revises: 3504d60e6a95
Create Date: 2026-01-09 19:30:27.452791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9556163367'
down_revision: Union[str, None] = '3504d60e6a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('used_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_quota_reset', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_downloading', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_downloading')
    op.drop_column('users', 'last_quota_reset')
    op.drop_column('users', 'used_quota')
    op.drop_column('users', 'daily_quota')
    # ### end Alembic commands ###
